import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'

import { cn } from '@/utils'

import '../globals.css'

export const metadata: Metadata = {
  title: '🍑🍟🥐🌭',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  return (
    <html lang={locale}>
      <body className={cn(GeistSans.className, 'h-screen')}>{children}</body>
    </html>
  )
}
